# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Connected', 'Connected'), ('Non-Responsive', 'Non-Responsive')], default='Connected', max_length=30)),
                ('macAddress', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketHash', models.CharField(default=None, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('Validated', 'Validated'), ('Non-Validated', 'Non-validated')], default='Non-Validated', max_length=30)),
                ('validationTime', models.DateTimeField()),
                ('validationPhone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Mobile')),
                ('validationTerminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Terminal')),
            ],
        ),
    ]
