# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-18 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='validationPhone',
        ),
    ]
