# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170218_2149'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MobileComsLog',
            new_name='MobileCommLog',
        ),
        migrations.AlterField(
            model_name='mobile',
            name='status',
            field=models.CharField(choices=[('Connected', 'Connected'), ('Non-Responsive', 'Non-Responsive')], default='Connected', max_length=30),
        ),
    ]
