# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-18 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_ticket_validationphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='validationTerminal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Terminal'),
        ),
    ]
