# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170218_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('time', models.DateTimeField(null=True)),
                ('auditorium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Auditorium')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='owner',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='status',
            field=models.CharField(choices=[('c', 'Connected'), ('n', 'Non-Responsive')], default='c', max_length=30),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='status',
            field=models.CharField(choices=[('c', 'Connected'), ('n', 'Non-Responsive')], default='c', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('v', 'Validated'), ('n', 'Non-Validated'), ('i', 'In Progress')], default='n', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='validationTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Event'),
        ),
    ]
