# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170221_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorium',
            name='address',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='ipAddress',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='token',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='ipAddress',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='owner',
            field=models.CharField(default='', max_length=30),
        ),
    ]
