# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170226_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Validated', 'Validated'), ('Non-Validated', 'Non-Validated'), ('In Progress', 'In Progress')], default='Non-Validated', max_length=30),
        ),
    ]
