# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170226_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilecommlog',
            name='mobileId',
        ),
        migrations.AddField(
            model_name='mobilecommlog',
            name='terminalId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Terminal'),
        ),
        migrations.AlterField(
            model_name='mobilecommlog',
            name='ticketId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketHash',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
