# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20170311_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
