# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 00:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_terminal_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='validationTerminal',
        ),
    ]
