# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_ticket_validationterminal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mobile',
        ),
    ]
